# Generated by Django 5.2.4 on 2025-07-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit or loss for this transaction', max_digits=10),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='wastage_reason',
            field=models.CharField(blank=True, choices=[('expired', 'Expired'), ('damaged', 'Damaged'), ('quality_issue', 'Quality Issue'), ('spoilage', 'Spoilage'), ('theft', 'Theft/Loss'), ('other', 'Other')], help_text='Reason for wastage', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price used for this transaction', max_digits=10),
        ),
    ]
