# Generated by Django 5.2.4 on 2025-07-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_buying_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='wastage_reason',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='wastage_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
