# Generated by Django 5.2.1 on 2025-05-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_client_supplier_stocktransaction_client_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='is_wastage',
            field=models.BooleanField(default=False),
        ),
    ]
