# Generated by Django 5.2 on 2025-07-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_warehouse_alter_stocktransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='ait_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='apply_taxes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
