# Generated by Django 5.2 on 2025-07-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_payment_payment_id'),
    ]

    operations = [
    ]
