# Generated by Django 5.2.1 on 2025-06-19 11:51

from django.db import migrations

def copy_price_to_buying_selling(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    for product in Product.objects.all():
        if product.price is not None:
            product.buying_price = product.price
            product.selling_price = product.price
            product.save(update_fields=['buying_price', 'selling_price'])

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_buying_price_product_selling_price_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_price_to_buying_selling),
    ]
