# Generated by Django 5.2 on 2025-07-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_generate_payment_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Unique transaction identifier', max_length=20, null=True, unique=True),
        ),
    ]
