# Generated by Django 5.2.1 on 2025-06-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_copy_price_to_buying_selling'),
        ('inventory', 'add_wastage_field'),
    ]

    operations = [
    ]
