# Generated by Django 5.2.1 on 2025-06-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_merge_20250628_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='wastage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
