# Generated by Django 5.2 on 2025-07-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_wastagerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='wastage_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional wastage cost beyond the item value (e.g., disposal fees)', max_digits=10),
        ),
        migrations.DeleteModel(
            name='WastageRecord',
        ),
    ]
