# Generated by Django 5.2.1 on 2025-06-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stocktransaction_wastage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='wastage',
        ),
    ]
