# Generated by Django 5.2 on 2025-07-10 09:55

from django.db import migrations


def fix_wastage_profit_loss(apps, schema_editor):
    """
    Fix the profit_loss calculation for wastage transactions.
    For all existing wastage transactions, set profit_loss = -total_price
    """
    StockTransaction = apps.get_model('inventory', 'StockTransaction')
    
    # Get all wastage transactions
    wastage_transactions = StockTransaction.objects.filter(transaction_type='wastage')
    
    # Update each transaction's profit_loss to match the negative of total_price
    for transaction in wastage_transactions:
        transaction.profit_loss = -transaction.total_price
        transaction.save(update_fields=['profit_loss'])
    
    print(f"Fixed profit_loss for {wastage_transactions.count()} wastage transactions.")


def reverse_fix(apps, schema_editor):
    """
    This is a reversible migration, but we don't need to do anything in reverse
    because there's no way to know what the original values were.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_stocktransaction_wastage_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_wastage_profit_loss, reverse_fix),
    ]
