# Generated by Django 5.2.1 on 2025-06-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_stocktransaction_wastage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='wastage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
