# Generated by Django 5.2.1 on 2025-07-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stocktransaction_wastage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-date'], 'permissions': (('view_reports', 'Can view reports'), ('export_reports', 'Can export reports to CSV/PDF'), ('print_reports', 'Can print reports'))},
        ),
    ]
