# Generated by Django 5.2.4 on 2025-07-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_fix_wastage_profit_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku', 'warehouse')},
        ),
    ]
