# Generated by Django 5.2.1 on 2025-07-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_stocktransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Payment Due')], default='PAID', max_length=10),
        ),
    ]
