# Generated by Django 5.2.1 on 2025-07-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stocktransaction_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='payment_status',
        ),
    ]
